SELECT * FROM MARKETING;

-- DATA CLEANING

Select 
sum(case when age = null then 1 else 0 end) as agenullcount,
sum(case when income = null then 1 else 0 end) as incomenullcount,
sum(case when conversion = null then 1 else 0 end) as conversionnullcount,
sum(case when gender = null then 1 else 0 end) as gendernullcount
from marketing;


-- TREAT MISSING
/*
UPDATE MARKETING
SET INCOME= AVG(INCOME)
WHERE INCOME=NULL;
*/

-- TOTAL RECORDS

SELECT COUNT(*) FROM MARKETING;

-- 8000

-- TOTAL CONVERSIONS

SELECT CONVERSION FROM MARKETING;

SELECT SUM(CONVERSION) AS TOTALCONVERSION FROM MARKETING;

-- 7012

-- CONVERSION RATE

SELECT AVG(CONVERSIONRATE) AS AVGCONVRATE FROM MARKETING;

-- 0.104

SELECT * FROM MARKETING;

SELECT SUM(CONVERSION)*100 / COUNT(*) FROM MARKETING;

-- 87% IS THE CONVERSION RATE


-- GENDER WISE CONVERSION RATE

SELECT COUNT(*) AS MCOUNT  FROM MARKETING
WHERE GENDER='MALE';

-- 3161 MALE CUSTOMERS
SELECT COUNT(*) AS MCOUNT  FROM MARKETING
WHERE GENDER='FEMALE';

-- 4839


SELECT (SUM(CONVERSION))/ 3161 FROM MARKETING
WHERE GENDER='MALE';


SELECT SUM(CONVERSION) FROM MARKETING
WHERE GENDER='MALE';
-- 2772

SELECT SUM(CONVERSION) FROM MARKETING
WHERE GENDER='FEMALE';
-- 4240

SELECT (SUM(CONVERSION))/ 4839 FROM MARKETING
WHERE CONVERSION = 1;

-- 144


SELECT ( SUM(CONVERSION)*100 / 3161 )AS MALECONVRATE
FROM MARKETING
WHERE CONVERSION = 1;

-- 221



-- 0.8762  FOR FEMALE CONVRATE

-- 0.8769 FOR MALE CONVRATE


-- SUCCESSFUL CONVERSION RATE

-- CAMPAIGN CHANNEL WISE CONVERSION RATE


SELECT CAMPAIGNCHANNEL,AVG(CONVERSIONRATE) AS AVGRATE  FROM MARKETING
GROUP BY CampaignChannel;


-- GENDER WISE SUCCESSFUL CONVERSION
SELECT GENDER, SUM(CONVERSION)*100.00 / 
(SELECT SUM(CONVERSION) AS TOTALCONV FROM MARKETING) AS SUMCON
FROM MARKETING
GROUP BY GENDER;



SELECT SUM(CONVERSION) FROM MARKETING;
-- 7012

-- CAMPAIGNCHANNEL
SELECT CampaignChannel, SUM(CONVERSION)*100.00 / 
(SELECT SUM(CONVERSION) AS TOTALCONV FROM MARKETING) AS CONVERSIONRATE
FROM MARKETING
GROUP BY CampaignChannel
ORDER BY CONVERSIONRATE DESC;

/*

CampaignChannel	   CONVERSIONRATE
Referral	       21.6486023958927
PPC	               20.8357102110667
SEO	               19.3810610382201
Email	           19.3240159726183
Social Media	   18.8106103822019

*/

